In [31]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import pandas as pd

In [32]:
train_data=pd.read_csv("train.csv")
test_data=pd.read_csv("test.csv")

In [33]:
features=["Sex","Pclass","Age","SibSp","Parch"]
y=train_data["Survived"]
train_data=train_data[features]
train_data=train_data.fillna(40)
train_data["Sex"]=(train_data["Sex"]=="male")*1
x_data=torch.tensor([list(train_data.loc[each]) for each in list(train_data.index)]).float()
print(x_data)

tensor([[ 1.,  3., 22.,  1.,  0.],
        [ 0.,  1., 38.,  1.,  0.],
        [ 0.,  3., 26.,  0.,  0.],
        ...,
        [ 0.,  3., 40.,  1.,  2.],
        [ 1.,  1., 26.,  0.,  0.],
        [ 1.,  3., 32.,  0.,  0.]])


In [34]:
model=nn.Sequential(nn.Linear(5,10),nn.Linear(10,1),nn.Sigmoid())

In [35]:
criterion=nn.BCELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)

In [36]:
y=torch.tensor(y).float()
min_loss=100000000

In [37]:
for epoch in range(15000):
    optimizer.zero_grad()
    o=model(x_data.float())
    loss=criterion(o,y)
    loss.backward()
    optimizer.step()
    if epoch%10000==0:
        print(epoch)
    min_loss=min(min_loss,loss.item())

c:\users\ansh\appdata\local\programs\python\python38\lib\site-packages\torch\nn\modules\loss.py:516: UserWarning: Using a target size (torch.Size([891])) that is different to the input size (torch.Size([891, 1])) is deprecated. Please ensure they have the same size.
  return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)


0
10000


In [38]:
model(x_data[18])

tensor([0.6343], grad_fn=<SigmoidBackward>)

In [39]:
model(x_data).detach().numpy()

array([[0.13112235],
       [0.91341263],
       [0.71804625],
       [0.9179257 ],
       [0.13496259],
       [0.12398698],
       [0.42890492],
       [0.10535989],
       [0.68705416],
       [0.8644615 ],
       [0.7334907 ],
       [0.904903  ],
       [0.17286064],
       [0.07278772],
       [0.7628955 ],
       [0.7925795 ],
       [0.08123744],
       [0.27202722],
       [0.6343095 ],
       [0.6597072 ],
       [0.29174325],
       [0.2957859 ],
       [0.75935274],
       [0.5548559 ],
       [0.5893402 ],
       [0.5229948 ],
       [0.12398698],
       [0.35592964],
       [0.6597072 ],
       [0.12398698],
       [0.49662018],
       [0.9102803 ],
       [0.6597072 ],
       [0.18377279],
       [0.48343068],
       [0.41602746],
       [0.12398698],
       [0.17009227],
       [0.6265521 ],
       [0.70723826],
       [0.5927577 ],
       [0.8319534 ],
       [0.12398698],
       [0.87416226],
       [0.7448234 ],
       [0.12398698],
       [0.09605774],
       [0.659

In [40]:
test=test_data[features].copy()
test["Sex"]=(test["Sex"]=="male")*1
test.fillna(0)
x_data=torch.tensor([list(test.loc[each]) for each in list(test.index)]).float()

In [41]:
answer=model(x_data).detach().numpy()
test_data["Survived"]=(answer>=0.5)*1
test_data=test_data[["PassengerId","Survived"]]

<ipython-input-41-3cd4fb67705e>:2: RuntimeWarning: invalid value encountered in greater_equal
  test_data["Survived"]=(answer>=0.5)*1


In [42]:
test_data.head(40)

PassengerId  Survived
0           892         0
1           893         1
2           894         0
3           895         0
4           896         1
5           897         0
6           898         1
7           899         0
8           900         1
9           901         0
10          902         0
11          903         0
12          904         1
13          905         0
14          906         1
15          907         1
16          908         0
17          909         0
18          910         1
19          911         1
20          912         0
21          913         0
22          914         0
23          915         1
24          916         1
25          917         0
26          918         1
27          919         0
28          920         0
29          921         0
30          922         0
31          923         0
32          924         1
33          925         0
34          926         0
35          927         0
36          928         0
37          929         1
38          930         0
39          931         0

In [43]:
test_data.to_csv("submission2.csv",index=False)